version: '3'
services:
  vue:
    build: ./vue
    container_name: vue
    privileged: true
    restart: always
    volumes:
      - ./vue/www/myapp:/www/myapp
    ports:
      - 8080:8080
    networks:
      - frontend
    env_file:
      - ./.env
    command: [ "./start.sh" , $current_env] 

networks:
  frontend:
    driver: bridge